extends SceneTree

## Reproducible, original low-resolution item icons generated by Godot Image API.


func _init() -> void:
	var output_dir: String = "res://assets/ui/items"
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(output_dir))
	_save_daggers("%s/veilbound_daggers.png" % output_dir, Color("607a90"), Color("d5dee3"))
	_save_daggers("%s/ravenfang_daggers.png" % output_dir, Color("6f8194"), Color("eef5f6"))
	quit()


func _save_daggers(path: String, grip: Color, blade: Color) -> void:
	var image: Image = Image.create(16, 16, false, Image.FORMAT_RGBA8)
	image.fill(Color(0, 0, 0, 0))
	for y: int in [5, 10]:
		image.fill_rect(Rect2i(1, y, 9, 2), blade)
		image.fill_rect(Rect2i(9, y - 1, 2, 4), grip)
		image.fill_rect(Rect2i(11, y, 4, 2), Color("b98243"))
	image.set_pixel(0, 5, Color("eef5f6"))
	image.set_pixel(0, 10, Color("eef5f6"))
	var error: Error = image.save_png(path)
	if error != OK:
		push_error("Unable to save item icon %s: %s" % [path, error_string(error)])
